### ISSUE TITLE
Authentifier un utilisateur

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#1]
En tant qu'UTILISATEUR, je veux m'authentifier pour avoir accès à mes fonctionnalités dans eXm.
Pré-conditions: L'Utilisateur a une connexion internet, et est sur la page d'accueil de eXm.
Déclencheur: l'Utilisateur sélectionne "M'authentifier".
Déroulement:
1. eXm affiche la page d'authentification avec:
   - Code d'utilisateur: 
      - Si Étudiant, format = les 5 derniers chiffres du code de dossier;
      - Si Admin ou Professeur, format = (nom en minuscules) <Nom de famille>_<première lettre du prénom>, ex. "trudel_s" pour Trudel Sylvie, "ajib_w" pour Ajib Wessam.
   - Mot de passe: entre 6 et 16 caractères, au moins une lettre, au moins un chiffre, etc... (mêmes règles de mot de passe que pour n'importe quel utilisateur).
      - Pour un étudiant, quand on crée l'utilisateur, le mot de passe par défaut sera <les 3 premières lettres de son nom de famille en MAJUSCULES><jour de naissance sur 2 chiffres><Mois de naissance sur 2 chiffres>. Ex. Josiane Latrimouille née le 2 mars: LAT0203.
1. L'Utilisateur entre son code d'accès et son mot de passe.
1. eXm valide qu'ils sont corrects et affiche les options de menu contextuelles au privilèges du type d'utilisateur --> Sinon (authentification en échec), message d'erreur "Code d'utilisateur ou mot de passe invalide".
1. Si l'Utilisateur authentifié est "Administrateur" dans son profil, alors eXm affiche les options de menus suivants:
   - Utilisateurs: pour afficher la liste des utilisateurs (Administrateurs, Professeurs et Étudiants) et en faire la gestion;
   - Cours: pour afficher la liste des cours et en faire la gestion;
   - Sessions: pour afficher la liste des sessions et en faire la gestion;
   - Groupes: pour afficher la liste des groupes et en faire la gestion;
   - Cours-groupes: pour afficher la liste des cours-groupes d'une session donnée et en faire la gestion.
1. Si l'Utilisateur est [aussi] un Professeur, alors eXm affiche l'option suivante:
   - Mes examens (professeur): Pour afficher la liste des examens et en faire la gestion (Option "Lister les examens (Prof)" démarre si on sélectionne cette option).
1. Si l'Utilisateur est un Étudiant, alors eXm affiche l'option suivante:
   - Mes examens (étudiant): pour accéder à la liste des examens des cours-groupes-session auxquels l'étudiant est ou a été inscrit.

**Comment by josephclaudnerson** [comment]
Liste des cas de test:
1. L'utilisateur s'authentifie correctement --> OK.
1. L'Utilisateur entre un mauvais code d'utilisateur --> Message d'erreur.
1. L'Utilisateur entre un mauvais mot de passe --> Message d'erreur.
1. L'utilisateur authentifié est Admin --> Le menu de l'Admin s'affiche.
1. L'utilisateur authentifié est Professeur --> Le menu du Professeur s'affiche.
1. L'utilisateur authentifié est Étudiant --> Le menu de l'étudiant s'affiche.
1. L'utilisateur authentifié est Admin et Professeur --> Les menus de l'Admin et du Professeur s'affichent.
