### ISSUE TITLE
Créer/Modifier un étudiant (Admin)

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#10]
En tant qu'Administrateur, je veux Créer un étudiant, afin de l'affecter plus tard à des cours-groupes et qu'il puisse faire ses examens.

Pré-conditions: L'Admin est authentifié.
Déclencheur: L'Admin a sélectionné l'option "Étudiants", eXm a affiché la liste des étudiants, puis l'Admin a sélectionné un étudiant ou a sélectionné l'option "Ajouter+".
Déroulement:
1. eXm affiche la page de Création/Modification d'un étudiant, avec les informations existantes si un étudiant existant avait été sélectionné.
1. L'Admin saisit les champs suivants:
   1. Le numéro de dossier (format: à vérifier auprès de l'INUKA; a priori 20 ou 30 caractères devraient être suffisants)
      1. eXm lit si cet étudiant existe dans la BD.
      1. S'il existe, afficher ses informations. Sinon, on est en mode création.
   1. Nom de famille (50 caractères).
   1. Prénom(s) (50 caractères).
   1. Statut (liste déroulante: Actif, Inactif, etc. à vérifier auprès de INUKA).
   1. Niveau d'études (liste déroulante: Certificat, Licence, Maitrise, Doctorat, autres?).
   1. Programme d'études (liste déroulante selon le niveau d'études:  insérer la liste des programmes de l'INUKA dans une table de la BD, avec code du programme et son titre).
1. L'Admin clique sur "Enregistrer".
1. eXm enregistre la fiche de l'étudiant.

**Comment by strudelauxpommes** [comment]
Liste des cas de test:
1. Créer un nouvel étudiant où tous les champs sont OK.
1. Créer un étudiant en omettant de répondre au Statut --> Message "Le statut est obligatoire".
1. Créer un étudiant en omettant de répondre au Niveau d'études --> Message "Le niveau d'études est obligatoire".
1. Créer un étudiant en omettant de répondre au Programmes d'études --> Message "Le programme d'études est obligatoire".
