### ISSUE TITLE
Créer un professeur (Admin)

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#11]
En tant qu'Administrateur, je veux créer un professeur afin de pouvoir lui attribuer plus tard des cours-groupes et qu'il y développe ses examens.

Pré-condition: L'utilisateur est authentifié en tant qu'Administrateur du système.
Déclencheur: L’Administrateur sélectionne l'option "Professeurs".
Déroulement:
1. eXm affiche la page de Création/Modification des professeurs, avec les informations existantes si un Professeur existant avait été sélectionné.
L'Administrateur saisit les champs suivants:
        Le numéro de dossier du professeur (format: à vérifier auprès de l'INUKA; a priori 20 ou 30 caractères devraient être suffisants)
            eXm lit si ce professeur existe dans la BD.
            S'il existe, eXm va afficher ses informations. Sinon, on passe en mode création.
        Nom de famille (50 caractères).
        Prénom(s) (50 caractères).
       Statut (liste déroulante: Actif, Inactif, etc. à vérifier auprès de L'INUKA).
        Niveau d'études (liste déroulante: Licence, Maitrise, Doctorat, autres?).
    L'Administrateur clique sur "Enregistrer".
    eXm enregistre la fiche du Professeur.

**Comment by strudelauxpommes** [comment]
Liste des cas de test:
1. Créer un professeur correctement (il n'existait pas avant et tous les champs requis sont adéquatement remplis).
1. Tenter de créer un professeur qui existe déjà --> Message d'erreur
