### ISSUE TITLE
Créer un examen (Professeur)

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#13]
En tant que Professeur, je veux Créer un examen, afin de le rendre disponible aux étudiant à une date et une heure données, et pour une durée déterminée.

Déclencheur: À partir de la Liste des examens, le professeur clique sur [+] pour ajouter un examen ou clique sur une description d'un examen existant pour le modifier.

Déroulement:
1. eXm affiche la page "Créer/Modifier un examen". Si un examen existant avait été sélectionné, alors les valeurs des champs de cet examen s'affichent.
1. Le professeur entre ou modifie les champs suivants:
   - Description (20 caractères?) (Obligatoire)
   - Session: liste déroulante des sessions actives (ex. Aut-2018, Été-2019, Hiv-2018, etc., en ordre d'année et session Hiv/Été/Aut; le choix "Indéterminé" doit être le 1er choix disponible). Ce champs est optionnel, sauf si on veut activer l'examen.
   - Cours: liste déroulante de la liste des cours attribués à ce professeur (pour la session sélectionnée s'il y en a une). Ce champs est optionnel, sauf si on veut activer l'examen.
   - Groupe: liste déroulante de la liste des groupes de ce cours attribués à ce professeur. Ce champs est optionnel, sauf si on veut activer l'examen.
   - Paramètres relatifs aux questions et réponses:
      - (Case à cocher) Randomiser les choix de réponses multiples
      - (Case à cocher) Randomiser les questions par section de l'examen
   - Paramètres d'activation de l'examen (non accessibles s'il manque la session, le cours, et le groupe et s'il n'y a pas de questions):
      - Date de l'examen: format de la date selon les préférences du profil de l'utilisateur (ex. JJ-MM-AAAA ou AAAA-MM-JJ ou autre).
      - Heure de l'examen: HH:mm (ex. 15:00 ou 15:30).
      - Durée de l'examen: HH:mm (ex. 2:30 ou 3:00).
   - [Enregistrer] --> eXm enregistre les informations de l'examen et retourne à la liste des examens, mise à jour avec les nouvelles informations.
   - [Annuler].
   - [Questions de cet examen] --> eXm enregistre les informations de l'examen et déclenche la page "Lister les question d'un examen".

**Comment by josephclaudnerson** [comment]
Liste des cas de test:
1. Créer un examen, sans date d'activation --> OK.
1. Créer un examen, avec un cours-groupe-session et les paramètres d'activation dans le futur --> OK.
1. Créer un examen, avec cours-groupe-session dont la date d'activation est passée --> Message d'erreur "Cette date et heure sont dans le passé. Veuillez mettre une date et heure dans le futur."
1. Modifier un examen qui n'a pas de date d'activation --> OK.
1. Modifier un examen dont la date d'activation est dans le futur --> OK.
1. Modifier un examen dont la date-heure d'activation est passée, ne serait-ce que de une minute --> Permettre la modification seulement si AUCUN étudiant n'a répondu à cet examen ou n'est en train de faire cet examen. Sinon, message d'erreur "Il n'est pas possible de modifier un examen en cours d'exécution.  Il y a en ce moment XX étudiant(s) qui sont en train d'y répondre et XX étudiant(s) qui y ont répondu. "  (S'applique aussi aux questions de cet examen).
1. Pour valider les conditions d'avoir un examen, un professeur ne peut activer un examen que s'il est titulaire de ce cours-groupe-session.
