### ISSUE TITLE
Lister les examens

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#14]
En tant que PROFESSEUR, je veux LISTER MES EXAMENS, afin d'en FAIRE LA GESTION.
Pré-condition: Le professeur est authentifié dans eXm.
Déclencheur: Le professeur sélectionne l'option "Examens".
Déroulement:
- eXm affiche la liste des examens  en ordre chronologique inverse (le plus récent en premier) des cours-groupes avec les informations suivantes:
   - Semestre: code du semestre (les semestres ou sessions sont définis par l'administrateur de eXm de l'organisation dans les paramètres généraux). Ex. Automne-2017, Hiver-2018.
   - Cours-groupe: <Sigle>-<groupe> (ex. GEL500-010). Les sigles de cours, les groupes possibles et la liaison cours-groupe sont définis par l'administrateur.
   - Description (texte libre de 20 caractères --> OBLIGATOIRE et cliquable);
   - Langue [de l'examen], 2 ou 3 caractères (ex. FR, EN, HT);
   - Nombre de questions (cliquable: ouvre la fenêtre de "Liste des questions");
   - Nombre de points total;
   - Durée maximale (ex. 3h, 2h30, etc.);
   - Date et heure de son activation (ex. l'examen aura lieu le 2-07-2018; 15h-18h). Un examen non planifié aurait "--" à la place.
   - Date de dernière modification: format défini dans les paramètres de l'utilisateur (ex. aaaa-mm-jj, jj-mm-aaaa, mm/jj/aaaa).
- Si on ne distingue pas les groupes (ex. le même examen pour tous les étudiants de ce cours, même s'il y a plusieurs classes distinctes dans ce semestre), alors le groupe du cours-groupe sera "00".
- On peut ne pas avoir de cours pour un examen donné (ex. "Indéfini"), mais la description devient alors obligatoire.
- Pour exécuter "Modifier un examen", le professeur clique sur la description de l'examen à modifier, à condition qu'aucune réponse n'a été donnée.
- Pour exécuter "Créer un examen", le professeur clique sur le bouton [+].
- Pour supprimer un examen, le professeur clique sur le bouton [X] vis-à-vis l'examen à supprimer. eXm vérifie que l'examen n'a pas de question répondues et qu'il est plus vieux que 12 mois, puis demande une confirmation. Si l'examen a moins de 12 mois (période de conservation des examens et réponses, définie par l'administrateur) mais qu'aucune réponse n'existe, alors on demande la confirmation.
- Pour "Tester un examen", le professeur clique sur le bouton [T] et l'exécution du test de l'examen débute (autre fonctionnalité).

**Comment by strudelauxpommes** [comment]
Liste des cas de test:
1. Afficher une liste vide d'examen.
1. Après avoir créé un examen, afficher la liste.
1. Après avoir créé plusieurs examens, afficher la liste. Ils doivent être dans le bon ordre.
1. Supprimer un examen et vérifier qu'il n'est plus dans la liste.

**Comment by strudelauxpommes** [comment]
Dates d'activation et de dernière modification: Mettre la date sur une ligne et l'heure sur une 2e ligne, sans le T et sans le Z.
