### ISSUE TITLE
Effacer une question

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#17]
En tant que PROFESSEUR, je veux EFFACER UNE QUESTION, afin de finaliser UN EXAMEN.
Pré-conditions: Le professeur est authentifié dans eXm; on a affiché la liste des questions pour un examen donné.
Déclencheur: Le professeur sélectionne une question de l'examen;
                           - En mode de suppression, le professeur clique sur le bouton "EFFACER".
Déroulement:
1. Une fois que le professeur clique sur l'option "Effacer", il doit être en mesure de effacer la question voulue.
2. Le pop up apparait puis on demande au professeur de confirmer la supression de cette question.
3. Le professeur clique sur "yes" --> eXm efface la question, puis affiche la page la liste des questions de cet examen.
1. le professeur clique sur "no" pour "Annuler" la suppression-->eXm retourne à la page précédente (la liste des questions de cet examen).

**Comment by josephclaudnerson** [comment]
Liste des cas de test:
1. Sélectionner un examen
1. Sélectionner l'option "yes"pour confirmer la suppression
1. Sélectionner l'option "no"pour annuler la suppression
