### ISSUE TITLE
Créer une question (Professeur)

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#19]
En tant que PROFESSEUR, je veux Créer/Modifier une question afin de construire un examen.
Pré-conditions: Le professeur est authentifié et il a sélectionné un examen dont les informations détaillées ont été affichées. Le professeur a ensuite accédé à la liste des questions de cet examen.
Déclencheur: 
- En mode de création, le professeur clique sur le bouton "Ajouter (icône +)"
- En mode de modification, le professeur clique sur le bouton "Modifier (icône de crayon)"

Déroulement:
1. eXm affiche en entête, l'examen (Description, cours-groupe, session).
1. eXm affiche la question avec les informations suivantes:
   - La section de l'examen (identifiant et titre) --> Liste déroulante ou Nouvelle section: Pop-up pour créer une nouvelle section (identifiant et titre).
   - Libellé de la question (texte alphanumérique 512 caractères);
   - Image(s) à joindre dans un ordre établi (.JPG ou .PNG) --> chaque image est numérotée;
   - Type de question (et choix de réponses):
      - Vrai/Faux (1 bonne réponse parmi 2 choix - V/F) --> Montrer les réponses Vrai et Faux en radio-bouton avec la bonne réponse sélectionnée; Au moins une des réponses doit être sélectionnée comme étant la bonne.
      - Choix multiples (1 bonne réponse parmi une liste) --> Montrer les choix établis en radio-boutons avec la bonne réponse sélectionnée; Au moins une des réponses doit être sélectionnée comme étant la bonne.
      - Multiples réponses (n bonnes réponses parmi une liste) --> Montrer les choix établis en check-boxes avec les bonnes réponses sélectionnées; Au moins deux des réponses doivent être sélectionnées comme étant les bonnes.
      - Réponse courte textuelle (alphanumérique 30 caractères) --> Donner la bonne réponse; Préciser le nombre de réponses courtes demandées. Si > 1, alors donner un nombre de réponses attendues équivalent au nombre de réponses demandées.
      - Réponse courte numérique (999 999 999,99 ou Double Float); -> Donner la bonne réponse;
      - Réponse longue textuelle (alphanumérique 1024 caractères ou plus, ou moins); Ajouter des éléments de réponses ou une réponse type afin de guider la correction (peut être laissé vide)(Essentiel). --> (Important) Liste de réponses possibles avec un pointage (valeur attribuée selon la réponse, ex. la question vaut 5 points, mais la réponse précise que s'il manque tel ou tel élément, cela mérite 3 points). Cette liste de réponse permettra d'accélérer la correction à l'aveugle plus tard.
      - Associations (matching) --> OPTIONNEL (Souhaitable) --> 2 listes de choix avec identifiant unique; Réponses possibles: À chaque élément de gauche doit correspondre un élément de droite (paires de réponses) --> Exemple: une grille avec des radio-boutons sur 2 axes X et Y, un seul choix possible par colonne et par rangée;
      - (Optionnel) Combler les espaces: intercaler du texte avec des espaces de réponses et, pour chaque espace de réponse, donner la réponse attendue;
   - Pointage (numérique 999,99) = Nombre maximum de points quand l'étudiant a tout bon.
1. Le professeur entre ou modifie les informations de la question.
1. Le professeur clique sur "Enregistrer" --> eXm enregistre la question et ses dépendances puis affiche la page prête à entrer une autre question.
1. Quand le professeur a terminé, il clique sur "Annuler" --> eXm retourne à la page précédente (la liste des questions de cet examen).

**Comment by strudelauxpommes** [comment]
Liste des cas de test:
1. Créer une question de type Vrai/Faux. 
1. Créer une question de type Choix Multiple.
1. Créer une question de type Multiples réponses.
1. Créer une question de type Réponse courte textuelle.
1. Créer une question de type Réponse courte numérique.
1. Créer une question de type Réponse longue textuelle.
1. Créer une question de type Association.

**Comment by strudelauxpommes** [comment]
Exemples de questions Vrai/Faux:
1. Haïti se trouve en Europe. Rép.: Faux
1. Au Canada, l'hiver est froid. Rép.: Vrai
1. Au Québec, la langue parlée la plus fréquente est le français. Rép.: Vrai

Exemples de questions à choix multiples (une seule bonne réponse parmi la liste, minimum de 2 éléments dans la liste --> radio-boutons):
1. Dans une équipe Agile applicant la méthode SCRUM, quel rôle est responsable de maintenir le carnet de produit:
   1. Le Scrum Master (non)
   1. Les membres de l'équipe (non)
   1. Le Product Owner (Oui!)
   1. Le directeur du développement (non)
   1. Les utilisateurs (non)
--> Règle pour correction automatique: il faut une seule réponse et que cette réponse soit la bonne pour obtenir les points liés à la question.

Exemple de question à multiples réponses (plus de 3 choix, au moins 2 réponses vraies --> check-boxes):
1. Quels sont les rôles au sein d'une équipe SCRUM:
   1. Scrum Master (Oui)
   1. Membres d'équipe (Oui)
   1. Directeur du développement (non)
   1. Utilisateurs (non)
   1. Product Owner (Oui)
--> Règle de correction automatique: chaque bonne réponse vaut le pro-rata du nombre de points de la question par rapport au nombre de bonnes réponses MOINS la moitié des points du pro-rata pour chaque mauvaise réponse.

Exemple de réponse courte textuelle:
Nommez l'activité SCRUM par laquelle l'équipe applique l'amélioration continue de son processus. Réponse attendue: "Rétrospective"

Exemple de réponse courte numérique:
En vous fiant aux données présentées sur le graphique, combien de _User Story Points_ l'équipe a-t-elle terminée entre le début du projet et la fin de l'itération #3? Réponse attendue: 62
