### ISSUE TITLE
Authentifier Etudiant

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#2]
En tant qu’Étudiant, je veux m'authentifier pour avoir accès à mes fonctionnalités dans eXm.
Pré-conditions: L’Étudiant  est sur la page d'accueil de eXm.
Déclencheur: L’étudiant sélectionne "M'authentifier".
Déroulement:
1. eXm affiche la page d'authentification avec:
  - Pour un étudiant, quand on crée l'utilisateur, le mot de passe par défaut sera <les 3 premières lettres de son nom de famille en MAJUSCULES><jour de naissance sur 2 chiffres><Mois de naissance sur 2 chiffres>. Ex. Josiane Latrimouille née le 2 mars: LAT0203.
1. L’Étudiant entre son code d'accès et son mot de passe.
1. eXm valide qu'ils sont corrects et affiche les options de menu contextuelles au privilèges de L’Étudiant --> Sinon (authentification en échec), message d'erreur "Code d'utilisateur ou mot de passe invalide".
1. l'Utilisateur est un Étudiant, alors eXm affiche l'option suivante:
   - Mes examens (étudiant): pour accéder à la liste des examens des cours-groupes-session auxquels l'étudiant est ou a été inscrit.

**Comment by josephclaudnerson** [comment]
Liste des cas de test:
1. L’Étudiant s'authentifie correctement --> OK.
1. L’Étudiant entre un mauvais code d'utilisateur --> Message d'erreur.
1. L’Étudiant entre un mauvais mot de passe --> Message d'erreur.
1. eXm affiche les examens de l’étudiant en tenant compte des cours-groupes-session auxquels l'étudiant est ou a été inscrit.
