### ISSUE TITLE
Modifier une question (Professeur)

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#20]
En tant que PROFESSEUR, je veux MODIFIER UNE QUESTION, afin de finaliser UN EXAMEN.
Pré-conditions: Le professeur est authentifié dans eXm; on a affiché la liste des questions pour un examen donné.
Déclencheur: Le professeur sélectionne une question de l'examen;
                           - En mode de modification, le professeur clique sur le bouton "Modifier (icône de crayon)".
Déroulement:
1. Une fois que le professeur clique sur l'option "Modifier", il doit être en mesure de modifié la question voulue.
2. Le professeur modifie les informations de la question.
3. Le professeur clique sur "Enregistrer" --> eXm enregistre la question et ses dépendances puis affiche la page prête à modifier une autre question.

- Quand le professeur a terminé, il clique sur "Annuler" --> eXm retourne à la page précédente (la liste des questions de cet examen).

**Comment by josephclaudnerson** [comment]
Liste des cas de test:
1. Modifier une question --> OK.
Les mêmes cas que la création de question s'appliquent.
