### ISSUE TITLE
Authentifier Professeur

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#3]
En tant que professeur, je veux m'authentifier pour avoir accès à mes fonctionnalités dans eXm.
Pré-conditions: Le professeur  est sur la page d'accueil de eXm.
Déclencheur: Le professeur sélectionne "M'authentifier".
Déroulement:
1. eXm affiche la page d'authentification avec:
   - Code du professeur: 
      - le Professeur, format = (nom en minuscules) <Nom de famille>_<première lettre du prénom>, ex. "trudel_s" pour Trudel Sylvie, "ajib_w" pour Ajib Wessam.
   - Mot de passe avec les règles en vigueur.
1. Le professeur entre son code d'accès et son mot de passe.
1. eXm valide qu'ils sont corrects et affiche les options de menu contextuelles au privilèges du professeur --> Sinon (authentification en échec), message d'erreur "Code d'utilisateur ou mot de passe invalide".
1. l'Utilisateur est un Professeur, alors eXm affiche l'option suivante:
   - Mes examens (professeur): Pour afficher la liste des examens et en faire la gestion.
1. eXm affiche les options de menus suivantes pour le professeur:
   -Examens: Lister les examens;
   - Cours: pour afficher la liste des cours ;
   - Sessions: pour afficher la liste des sessions ;
   - Cours-groupes: pour afficher la liste des cours-groupes d'une session donnée.

**Comment by josephclaudnerson** [comment]
Liste des cas de test:
1. Le professeur s'authentifie correctement --> OK.
1. Le professeur entre un mauvais code d'utilisateur --> Message d'erreur.
1. Le professeur entre un mauvais mot de passe --> Message d'erreur.
1. Le professeur s'authentifie --> Le menu du Professeur s'affiche.
