### ISSUE TITLE
Créer/Modifier un groupe cours (Admin)

### ISSUE THREAD

**Issue by JeanDanielPierre** [jprosystems/exm#8]
En tant qu'Admin, je veux créer des groupes  cours donnés afin de pouvoir y associer plus tard des professeurs et des étudiants.

Pré-condition: L'utilisateur est authentifié en tant qu'Administrateur du système
Déclencheur: L'utilisateur sélectionne l'option groupe cours.
Déroulement:
1. eXm demande la session: liste déroulante des sessions actives.
1. L'Admin sélectionne la session.
1. eXm affiche: la liste des cours, avec pour chacun:
   - leur groupe cours, vide si pas encore affecté
   - Professeur(s) affectés: Liste de noms, sélectionnés dans une liste déroulante, vide si pas encore affecté(s) (note: pour le moment, on limite à 3 noms)
1. L'Admin clique sur [+] pour ajouter un cours ou clique sur un groupe-cours  pour éditer ce groupe-cours au besoin.
1. eXm affiche le cours et demande le groupe pour ce cours.
1. L'Admin saisie le groupe (quelques caractères, selon le modèle de données) et le professeur dans une liste déroulante (pour le moment, Professeur 1, Professeur 2 et Professeur 3) et il enregistre.
1. eXm enregistre ce cours de ce groupe pour cette session.
1. eXm enregistre l'affectation des professeurs à ce groupe-cours.
1. eXm réaffiche la liste des cours-groupes de cette session en tenant compte des changements.

**Comment by strudelauxpommes** [comment]
Liste des cas de test:
1. Sélectionner un cours et y affecter un groupe valide qui n'existait pas pour ce cours (mode normal).
1. Sélectionner un cours et tenter d'y affecter un groupe qui existe déjà --> Message "Ce groupe est déjà associé à ce cours".
1. (pour une version ultérieure) Sélectionner un cours et tenter d'y affecter un groupe invalide --> Message "Ce groupe n'est pas valide. SVP choisir un groupe valide",
